<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGN1nmA8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGN1nmA8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGN1nmA8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGN1nmA8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGN1nmA8\App_KernelDevDebugContainer([
    'container.build_hash' => 'GN1nmA8',
    'container.build_id' => '3d28c5e0',
    'container.build_time' => 1630584810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGN1nmA8');
