<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMdXM05\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMdXM05/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAMdXM05.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAMdXM05\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAMdXM05\App_KernelDevDebugContainer([
    'container.build_hash' => 'AMdXM05',
    'container.build_id' => 'e2c3ff05',
    'container.build_time' => 1630567787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMdXM05');
